### ISSUE TITLE
Make 'view source' buttons more visible

### ISSUE THREAD

**Issue by tmattsso** [vaadin/elements-demo-resources#20]
E.g. on this page https://cdn.vaadin.com/vaadin-material-styles/1.2.0/demo/text-fields.html the source buttons aren't very visible. Please fix the styling to improve the situation. 

Jouni says: The code for that is here: https://github.com/vaadin/elements-demo-resources/blob/new-menu-and-styles/nice-demo-snippet.html#L234-L261

**Comment by samiheikki** [comment]
Most component libraries have similar button for viewing source, but the size seems to be bigger in all of them.

Examples:
- https://material.angular.io/components/form-field/overview
- https://material-ui.com/demos/app-bar/
- https://vuematerial.io/components/avatar

Created #21 to increase the size
